// Generated by `supabase gen types typescript` (via the Supabase MCP server).
// Do not edit by hand — regenerate after every migration.
// Project: ooutquthyezhkunstymn (monishan-portfolio)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      certifications: {
        Row: {
          created_at: string | null
          credential_id: string | null
          credential_url: string | null
          description: string | null
          expiry_date: string | null
          icon: string | null
          id: string
          image_url: string | null
          is_current: boolean | null
          is_published: boolean | null
          issue_date: string | null
          issuer: string
          sort_order: number | null
          title: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          credential_id?: string | null
          credential_url?: string | null
          description?: string | null
          expiry_date?: string | null
          icon?: string | null
          id?: string
          image_url?: string | null
          is_current?: boolean | null
          is_published?: boolean | null
          issue_date?: string | null
          issuer: string
          sort_order?: number | null
          title: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          credential_id?: string | null
          credential_url?: string | null
          description?: string | null
          expiry_date?: string | null
          icon?: string | null
          id?: string
          image_url?: string | null
          is_current?: boolean | null
          is_published?: boolean | null
          issue_date?: string | null
          issuer?: string
          sort_order?: number | null
          title?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      contact_messages: {
        Row: {
          admin_notes: string | null
          budget_range: string | null
          created_at: string | null
          email: string
          id: string
          ip_hash: string | null
          message: string
          name: string
          project_type: string | null
          referrer: string | null
          status: Database["public"]["Enums"]["message_status"] | null
          subject: string | null
          updated_at: string | null
          user_agent: string | null
        }
        Insert: {
          admin_notes?: string | null
          budget_range?: string | null
          created_at?: string | null
          email: string
          id?: string
          ip_hash?: string | null
          message: string
          name: string
          project_type?: string | null
          referrer?: string | null
          status?: Database["public"]["Enums"]["message_status"] | null
          subject?: string | null
          updated_at?: string | null
          user_agent?: string | null
        }
        Update: {
          admin_notes?: string | null
          budget_range?: string | null
          created_at?: string | null
          email?: string
          id?: string
          ip_hash?: string | null
          message?: string
          name?: string
          project_type?: string | null
          referrer?: string | null
          status?: Database["public"]["Enums"]["message_status"] | null
          subject?: string | null
          updated_at?: string | null
          user_agent?: string | null
        }
        Relationships: []
      }
      education: {
        Row: {
          created_at: string | null
          degree: string
          description: string | null
          end_date: string | null
          field_of_study: string | null
          grade: string | null
          icon: string | null
          id: string
          institution: string
          is_current: boolean | null
          is_published: boolean | null
          logo_url: string | null
          sort_order: number | null
          start_date: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          degree: string
          description?: string | null
          end_date?: string | null
          field_of_study?: string | null
          grade?: string | null
          icon?: string | null
          id?: string
          institution: string
          is_current?: boolean | null
          is_published?: boolean | null
          logo_url?: string | null
          sort_order?: number | null
          start_date?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          degree?: string
          description?: string | null
          end_date?: string | null
          field_of_study?: string | null
          grade?: string | null
          icon?: string | null
          id?: string
          institution?: string
          is_current?: boolean | null
          is_published?: boolean | null
          logo_url?: string | null
          sort_order?: number | null
          start_date?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      experiences: {
        Row: {
          company: string
          company_url: string | null
          created_at: string | null
          employment_type: string | null
          end_date: string | null
          highlights: string[] | null
          icon: string | null
          id: string
          is_current: boolean | null
          is_published: boolean | null
          location: string | null
          logo_url: string | null
          role: string
          sort_order: number | null
          start_date: string
          summary: string | null
          tech_stack: string[] | null
          updated_at: string | null
          work_mode: string | null
        }
        Insert: {
          company: string
          company_url?: string | null
          created_at?: string | null
          employment_type?: string | null
          end_date?: string | null
          highlights?: string[] | null
          icon?: string | null
          id?: string
          is_current?: boolean | null
          is_published?: boolean | null
          location?: string | null
          logo_url?: string | null
          role: string
          sort_order?: number | null
          start_date: string
          summary?: string | null
          tech_stack?: string[] | null
          updated_at?: string | null
          work_mode?: string | null
        }
        Update: {
          company?: string
          company_url?: string | null
          created_at?: string | null
          employment_type?: string | null
          end_date?: string | null
          highlights?: string[] | null
          icon?: string | null
          id?: string
          is_current?: boolean | null
          is_published?: boolean | null
          location?: string | null
          logo_url?: string | null
          role?: string
          sort_order?: number | null
          start_date?: string
          summary?: string | null
          tech_stack?: string[] | null
          updated_at?: string | null
          work_mode?: string | null
        }
        Relationships: []
      }
      page_views: {
        Row: {
          country: string | null
          created_at: string | null
          device: string | null
          id: string
          path: string
          project_id: string | null
          referrer: string | null
        }
        Insert: {
          country?: string | null
          created_at?: string | null
          device?: string | null
          id?: string
          path: string
          project_id?: string | null
          referrer?: string | null
        }
        Update: {
          country?: string | null
          created_at?: string | null
          device?: string | null
          id?: string
          path?: string
          project_id?: string | null
          referrer?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "page_views_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      posts: {
        Row: {
          body: string | null
          cover_image_url: string | null
          created_at: string | null
          excerpt: string | null
          id: string
          is_published: boolean | null
          published_at: string | null
          reading_minutes: number | null
          slug: string
          tags: string[] | null
          title: string
          updated_at: string | null
          view_count: number | null
        }
        Insert: {
          body?: string | null
          cover_image_url?: string | null
          created_at?: string | null
          excerpt?: string | null
          id?: string
          is_published?: boolean | null
          published_at?: string | null
          reading_minutes?: number | null
          slug: string
          tags?: string[] | null
          title: string
          updated_at?: string | null
          view_count?: number | null
        }
        Update: {
          body?: string | null
          cover_image_url?: string | null
          created_at?: string | null
          excerpt?: string | null
          id?: string
          is_published?: boolean | null
          published_at?: string | null
          reading_minutes?: number | null
          slug?: string
          tags?: string[] | null
          title?: string
          updated_at?: string | null
          view_count?: number | null
        }
        Relationships: []
      }
      profile: {
        Row: {
          availability_note: string | null
          available_for_work: boolean | null
          avatar_url: string | null
          bio_long: string | null
          bio_short: string | null
          clients_served: number | null
          created_at: string | null
          email: string | null
          full_name: string
          headline: string
          hero_intro: string | null
          id: string
          location: string | null
          og_image_url: string | null
          phone: string | null
          projects_completed: number | null
          resume_url: string | null
          roles: string[] | null
          updated_at: string | null
          whatsapp_message: string | null
          whatsapp_number: string | null
          years_experience: number | null
        }
        Insert: {
          availability_note?: string | null
          available_for_work?: boolean | null
          avatar_url?: string | null
          bio_long?: string | null
          bio_short?: string | null
          clients_served?: number | null
          created_at?: string | null
          email?: string | null
          full_name: string
          headline: string
          hero_intro?: string | null
          id?: string
          location?: string | null
          og_image_url?: string | null
          phone?: string | null
          projects_completed?: number | null
          resume_url?: string | null
          roles?: string[] | null
          updated_at?: string | null
          whatsapp_message?: string | null
          whatsapp_number?: string | null
          years_experience?: number | null
        }
        Update: {
          availability_note?: string | null
          available_for_work?: boolean | null
          avatar_url?: string | null
          bio_long?: string | null
          bio_short?: string | null
          clients_served?: number | null
          created_at?: string | null
          email?: string | null
          full_name?: string
          headline?: string
          hero_intro?: string | null
          id?: string
          location?: string | null
          og_image_url?: string | null
          phone?: string | null
          projects_completed?: number | null
          resume_url?: string | null
          roles?: string[] | null
          updated_at?: string | null
          whatsapp_message?: string | null
          whatsapp_number?: string | null
          years_experience?: number | null
        }
        Relationships: []
      }
      projects: {
        Row: {
          accent_gradient: string | null
          body: string | null
          category: string | null
          client_name: string | null
          completed_on: string | null
          cover_image_url: string | null
          created_at: string | null
          gallery_urls: string[] | null
          icon: string | null
          id: string
          is_featured: boolean | null
          is_published: boolean | null
          live_url: string | null
          outcome: string | null
          problem: string | null
          repo_url: string | null
          resource_label: string | null
          resource_url: string | null
          role: string | null
          slug: string
          solution: string | null
          sort_order: number | null
          started_on: string | null
          status: Database["public"]["Enums"]["project_status"] | null
          subtitle: string | null
          summary: string
          tech_stack: string[] | null
          title: string
          updated_at: string | null
          view_count: number | null
        }
        Insert: {
          accent_gradient?: string | null
          body?: string | null
          category?: string | null
          client_name?: string | null
          completed_on?: string | null
          cover_image_url?: string | null
          created_at?: string | null
          gallery_urls?: string[] | null
          icon?: string | null
          id?: string
          is_featured?: boolean | null
          is_published?: boolean | null
          live_url?: string | null
          outcome?: string | null
          problem?: string | null
          repo_url?: string | null
          resource_label?: string | null
          resource_url?: string | null
          role?: string | null
          slug: string
          solution?: string | null
          sort_order?: number | null
          started_on?: string | null
          status?: Database["public"]["Enums"]["project_status"] | null
          subtitle?: string | null
          summary: string
          tech_stack?: string[] | null
          title: string
          updated_at?: string | null
          view_count?: number | null
        }
        Update: {
          accent_gradient?: string | null
          body?: string | null
          category?: string | null
          client_name?: string | null
          completed_on?: string | null
          cover_image_url?: string | null
          created_at?: string | null
          gallery_urls?: string[] | null
          icon?: string | null
          id?: string
          is_featured?: boolean | null
          is_published?: boolean | null
          live_url?: string | null
          outcome?: string | null
          problem?: string | null
          repo_url?: string | null
          resource_label?: string | null
          resource_url?: string | null
          role?: string | null
          slug?: string
          solution?: string | null
          sort_order?: number | null
          started_on?: string | null
          status?: Database["public"]["Enums"]["project_status"] | null
          subtitle?: string | null
          summary?: string
          tech_stack?: string[] | null
          title?: string
          updated_at?: string | null
          view_count?: number | null
        }
        Relationships: []
      }
      services: {
        Row: {
          created_at: string | null
          description: string | null
          icon: string | null
          id: string
          is_published: boolean | null
          sort_order: number | null
          starting_price: string | null
          title: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: string
          is_published?: boolean | null
          sort_order?: number | null
          starting_price?: string | null
          title: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: string
          is_published?: boolean | null
          sort_order?: number | null
          starting_price?: string | null
          title?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      site_settings: {
        Row: {
          created_at: string | null
          footer_note: string | null
          google_analytics_id: string | null
          id: string
          keywords: string[] | null
          maintenance_mode: boolean | null
          site_description: string | null
          site_title: string | null
          theme_mode: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          footer_note?: string | null
          google_analytics_id?: string | null
          id?: string
          keywords?: string[] | null
          maintenance_mode?: boolean | null
          site_description?: string | null
          site_title?: string | null
          theme_mode?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          footer_note?: string | null
          google_analytics_id?: string | null
          id?: string
          keywords?: string[] | null
          maintenance_mode?: boolean | null
          site_description?: string | null
          site_title?: string | null
          theme_mode?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      skill_categories: {
        Row: {
          created_at: string | null
          icon: string | null
          id: string
          is_published: boolean | null
          name: string
          sort_order: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          icon?: string | null
          id?: string
          is_published?: boolean | null
          name: string
          sort_order?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          icon?: string | null
          id?: string
          is_published?: boolean | null
          name?: string
          sort_order?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      skills: {
        Row: {
          category_id: string | null
          created_at: string | null
          icon: string | null
          id: string
          is_core: boolean | null
          is_published: boolean | null
          name: string
          proficiency: number | null
          sort_order: number | null
          updated_at: string | null
          years_used: number | null
        }
        Insert: {
          category_id?: string | null
          created_at?: string | null
          icon?: string | null
          id?: string
          is_core?: boolean | null
          is_published?: boolean | null
          name: string
          proficiency?: number | null
          sort_order?: number | null
          updated_at?: string | null
          years_used?: number | null
        }
        Update: {
          category_id?: string | null
          created_at?: string | null
          icon?: string | null
          id?: string
          is_core?: boolean | null
          is_published?: boolean | null
          name?: string
          proficiency?: number | null
          sort_order?: number | null
          updated_at?: string | null
          years_used?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "skills_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "skill_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      social_links: {
        Row: {
          created_at: string | null
          icon: string | null
          id: string
          is_published: boolean | null
          label: string | null
          platform: string
          sort_order: number | null
          updated_at: string | null
          url: string
        }
        Insert: {
          created_at?: string | null
          icon?: string | null
          id?: string
          is_published?: boolean | null
          label?: string | null
          platform: string
          sort_order?: number | null
          updated_at?: string | null
          url: string
        }
        Update: {
          created_at?: string | null
          icon?: string | null
          id?: string
          is_published?: boolean | null
          label?: string | null
          platform?: string
          sort_order?: number | null
          updated_at?: string | null
          url?: string
        }
        Relationships: []
      }
      testimonials: {
        Row: {
          author_avatar_url: string | null
          author_company: string | null
          author_name: string
          author_role: string | null
          created_at: string | null
          id: string
          is_published: boolean | null
          quote: string
          rating: number | null
          sort_order: number | null
          source_url: string | null
          updated_at: string | null
        }
        Insert: {
          author_avatar_url?: string | null
          author_company?: string | null
          author_name: string
          author_role?: string | null
          created_at?: string | null
          id?: string
          is_published?: boolean | null
          quote: string
          rating?: number | null
          sort_order?: number | null
          source_url?: string | null
          updated_at?: string | null
        }
        Update: {
          author_avatar_url?: string | null
          author_company?: string | null
          author_name?: string
          author_role?: string | null
          created_at?: string | null
          id?: string
          is_published?: boolean | null
          quote?: string
          rating?: number | null
          sort_order?: number | null
          source_url?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      message_status: "NEW" | "READ" | "REPLIED" | "ARCHIVED" | "SPAM"
      project_status: "LIVE" | "IN_PROGRESS" | "ARCHIVED" | "CONCEPT"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      message_status: ["NEW", "READ", "REPLIED", "ARCHIVED", "SPAM"],
      project_status: ["LIVE", "IN_PROGRESS", "ARCHIVED", "CONCEPT"],
    },
  },
} as const
